version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: '123'
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
